language: python
python:
- 3.5
cache:
  apt: true
  pip: true
before_install:
- pip install --upgrade pip setuptools
install:
- pip install -e .[dev]
- pip install pytest pytest-cov flake8
script:
- flake8 --exclude build
- py.test --cov pyhocr --cov-report term-missing
deploy:
  provider: pypi
  user: "mojtaba"
  distributions: bdist_wheel
  edge:
    branch: v1.8.45
  password:
    secure: "Mxt9/4cigWirUP5QVkqwAQ3rKWaoYYgsM4O5NCapSU+sCheIX5W60Q6aa4xQLV39IHkynLkF0VTmrdiWDnNogvdmLe88qPAcrpUTPYHHeeqR/YwgCBV84Gp10BQNzuSxE0TbGscoXAQiYe7DNzSWK6xecE4V/P+VvS1osAktyiAPeUN6RtRLCr97g/Kr0w8n6SVO2EFrUliAVkQe7pLg/UmeC2VORDz6weg13KkQprrCopGjL2bBiTv2JB251Ocg54tq2okNEKUR4UQXcXBZJa9K10F4HrK1BjMNKkjzjsdLwGyQxtJeQsudBn2NncYpEW088ALLpStu8NqPfnkEEMTmgT7nc9bjc0Q+Sh3xHewJkWwuppia1lmLYzoY04tXcrrgafVghen4zjs5K7f3pQ2mmu6Tv3DuRH08iH7ORV8nDaqW/Qza6t93nAi1jVaMTMg4gQ54gGzvn68zIEeK0WoD+521lyXhQoOEdfYAbdiTT6CdyDzDW13EcB4RElaYPXHPyRJ/DIspisqluowDDAk4qKOrpWd6eSCqDlPgB1NXcXE6cfVUUAKZaeaPtsumqhMoc160tAqMw2KOdiOufWv1BhYDMF/mPxCKB4TeIvbGSHYRlOX8TJ5k/BTG3HJ9X6VJqiYAUGJQ7Ct5fwCCLSiXwFOwMU9NJryUrMhH5i4="
