language: python
python:
- 3.5
cache:
  apt: true
  pip: true
before_install:
- pip install --upgrade pip setuptools
install:
- pip install -e .[dev]
- pip install pytest pytest-cov flake8
script:
- flake8 --exclude build
- py.test --cov hocr --cov-report term-missing
deploy:
  provider: pypi
  user: "mojtaba"
  password:
    secure: "N5gbHLSPo5UBBXh5m1wxxcF/Ew2ZnIlckOTOjeQ5FtGo+LS8VtQ6EsJCUUiihOrO1My9WEnyUsBIFG/Q9veM6XbKgdiOEAj3ukav33V1bqnLrCaftHB8U4WMK9Ye4ktJ05XN2SGiM3LBj7kQxH9PkqDGqbL5R+ix+D6ag0/JWFqD+mLfFw5ihA1MqdY1SGRCLMYbnPUL8NNgpZTSA+ugs6C1HcsXq/vGCIgTNRzitX0GzW0V6Om0ly/NT70BSpzcKYCJibjukmUTqBURhJtaEXOk97ol+y44KETsYXdDldo0AlYPMuzhtsj9mCG9F0C2KHRqX4p+y88X2N4+OBe3pLIv+iFwIQtPR+AqgAx+uz+PN+a1B8tZ2yVYVzrQoHg3mAGMFl/Dse0Ee+4J9uF7XFM+edq52UsYcaqYtFCa4fhYNrKXOG2KUBtjzjbHHoSFM5ZF5XPrm75xRYtF3s4LQMtGWhy84R5uYfMJpoEODYYPb1YKGdSdNNBX5MdIw5rlhO6HzBIrKz5zch/67cGCAjV4yhyjbqDfxgNW45H/2lYeuBJCgTV7azfYoj6pyvCRNfRGwB1WdTufGBuO2/O6XYDh/LMPgxGgMW6LmFK7VvauGvA7AHxZpf5VLQtmGZQFXJkDKYHyt6PriOrzuKDrypD2mq1LFdfW3JjHZi+o51U="
