language: python
python:
- 3.5
cache:
  apt: true
  pip: true
before_install:
- pip install --upgrade pip setuptools
install:
- pip install -e .[dev]
- pip install pytest pytest-cov flake8
script:
- flake8 --exclude build
- py.test --cov pyhocr --cov-report term-missing
deploy:
  provider: pypi
  user: "mojtaba"
  password:
    secure: "DdWYnTSfSsf64qiNXe3vwLUpyi+jhNWunHQbVveNPpU46ruBjFMwzvYbZuUX5/aJZPO0au/MHBCaQ15Z8DicxPyGCnI97SzH4hXaaKkHbDu75BEgxBvHaHBmQFI4Cwcu4+1p0xdep4o06Ap22Vc5IAYDw1yHB7BFMiAX3l8xXddNprl2RCx7l51A2FLm8Jr8IzfzMf6ABJZgQ4MZ8zpFXuSt5CXIdLNXUSBFEd3Zmxo8r6LM/GFx2JLZgwdlyper7sl5kTOTiFQKmWqP4SDpOTP19oeF+ELWBtwFi3YxC/MwswonZCB47Tobqauww+2Fs0kcT/CHVsTJsU/dauja+SOLb8v9+Aljs+z6db/lRgpiCa0dhRkFjDO+oo8fx3bv5An8ZB1MBXxbl4pCxyWOoD5sQDwQgwSuvw0SH0GWsT4NGSqNgq9Zan7iLbWJP/kEnDlbRspPT96fipfZEPvmFJSk1b5FtpEsHXHonq1Prs+FVfHr5s5V8gUiDqcy1V3AitWfUcH/8JPaZR2MIWyvZLa7lu+5T0o0UQaQ88ox9Fu/8AB4vKZbVa8VqxWifylP33+9EG1rp8KNO15H73X5eVGxqsLRvUNhJx5thHF6DhZ6DwnhfgOEzs6A44x4HVFiFnKJGULws2MPH3C9l/Rq6ZUhklBmnxoXYqcumu6C5LI="
